-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(5);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(2);
